[package]
name = "fcrypt"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
argon2 = "0.5.3"
clap = { version = "4.5.42", features = ["derive"] }
rand = "0.9.2"
rpassword = "7.4.0"
uuid = { version = "1.17.0", features = ["v4"] }
walkdir = "2.5.0"
